### ISSUE TITLE
Open Session Error is thrown while connecting to databricks spark SQL from metabase

### ISSUE THREAD

**Issue by chandanmanjunath** [fhsgoncalves/metabase-sparksql-databricks-driver#1]
Steps I have followed are:

1.Installed metabase version 0.33.7.3

2.Downloaded jars **sparksql-databricks.metabase-driver.jar** and **simba-spark-jdbc41-2.6.3.1003.jar** and placed in /./plugins directory

from links:
[ https://github.com/fhsgoncalves/metabase-sparksql-databricks-driver](url)
and
[https://dl.bintray.com/ifood/third/simba/simba-spark-jdbc41/2.6.3.1003/simba-spark-jdbc41-2.6.3.1003.jar](url)

3.Restarted the metabase.

But it still displays same error while i am saving the database connection in add database page from metabase while connecting to spark SQL(databricks):

**[Simba]SparkJDBCDriver Error setting/closing session: Open Session Error.**

Along with this there is other java error stack also,not sure if it is related to spark SQL databricks connection. :

Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at java.base/sun.security.validator.PKIXValidator.(PKIXValidator.java:89)
at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110)
at com.simba.spark.hivecommon.utils.DSTrustManager.checkServerTrusted(Unknown Source)
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1510)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)

Please let me know how I can resolve this issue

**Comment by chandanmanjunath** [comment]
This issue is now resolved and we are able to establish connection, please follow the below link.

[https://discourse.metabase.com/t/connecting-databricks-spark-to-metabase/6274](url)
